@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.jm_potions.data_generate.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;